import {
  Client,
  Invoice,
  Lead,
  Video,
  VideoComment,
  ContentItem,
  Quote,
  Contract,
  DashboardStats,
  OnboardingChecklist,
} from "./types";

export const MOCK_CLIENTS: Client[] = [
  {
    id: "c1",
    name: "The Kelvin Kitchen",
    email: "hello@kelvinkitchen.co.uk",
    phone: "0141 555 0101",
    package: "Social Growth",
    monthlyValue: 850,
    status: "active",
    invoiceDay: 1,
    assignedTo: "Rohit",
    contractUrl: "#",
    portalActive: true,
    onboardingProgress: 100,
    monthlyProgress: 65,
    createdAt: "2025-09-01",
  },
  {
    id: "c2",
    name: "Finnieston & Co.",
    email: "bar@finniestonco.com",
    phone: "0141 555 0202",
    package: "Brand Builder",
    monthlyValue: 1200,
    status: "active",
    invoiceDay: 15,
    assignedTo: "Rohin",
    contractUrl: "#",
    portalActive: true,
    onboardingProgress: 100,
    monthlyProgress: 80,
    createdAt: "2025-10-15",
  },
  {
    id: "c3",
    name: "Glasgow Barbell Club",
    email: "info@glasgowbarbell.com",
    phone: "0141 555 0303",
    package: "Social Growth",
    monthlyValue: 750,
    status: "active",
    invoiceDay: 28,
    assignedTo: "Harpreet",
    portalActive: false,
    onboardingProgress: 62,
    monthlyProgress: 40,
    createdAt: "2026-01-10",
  },
  {
    id: "c4",
    name: "Pollok Padel Club",
    email: "admin@pollokpadel.com",
    package: "Starter",
    monthlyValue: 450,
    status: "paused",
    invoiceDay: 1,
    assignedTo: "Rohit",
    portalActive: false,
    onboardingProgress: 37,
    monthlyProgress: 30,
    createdAt: "2026-02-20",
  },
  {
    id: "c5",
    name: "West End Wanderlust",
    email: "hey@westendwanderlust.co.uk",
    phone: "0141 555 0505",
    package: "Brand Builder",
    monthlyValue: 1100,
    status: "active",
    invoiceDay: 10,
    assignedTo: "Rohin",
    contractUrl: "#",
    portalActive: true,
    onboardingProgress: 100,
    monthlyProgress: 55,
    createdAt: "2025-08-05",
  },
  {
    id: "c6",
    name: "Merchant City Eats",
    email: "info@merchantcityeats.com",
    package: "Starter",
    monthlyValue: 400,
    status: "churned",
    invoiceDay: 5,
    assignedTo: "Harpreet",
    portalActive: false,
    onboardingProgress: 100,
    monthlyProgress: 45,
    createdAt: "2025-06-01",
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv1",
    reference: "INV-2026-041",
    clientId: "c1",
    clientName: "The Kelvin Kitchen",
    amount: 850,
    dueDate: "2026-05-01",
    status: "unpaid",
    createdAt: "2026-04-01",
  },
  {
    id: "inv2",
    reference: "INV-2026-040",
    clientId: "c2",
    clientName: "Finnieston & Co.",
    amount: 1200,
    dueDate: "2026-04-15",
    status: "overdue",
    createdAt: "2026-03-15",
  },
  {
    id: "inv3",
    reference: "INV-2026-039",
    clientId: "c5",
    clientName: "West End Wanderlust",
    amount: 1100,
    dueDate: "2026-04-10",
    status: "overdue",
    createdAt: "2026-03-10",
  },
  {
    id: "inv4",
    reference: "INV-2026-038",
    clientId: "c3",
    clientName: "Glasgow Barbell Club",
    amount: 750,
    dueDate: "2026-04-28",
    status: "unpaid",
    createdAt: "2026-03-28",
  },
  {
    id: "inv5",
    reference: "INV-2026-037",
    clientId: "c1",
    clientName: "The Kelvin Kitchen",
    amount: 850,
    dueDate: "2026-04-01",
    status: "paid",
    paidAt: "2026-04-02",
    createdAt: "2026-03-01",
  },
  {
    id: "inv6",
    reference: "INV-2026-036",
    clientId: "c2",
    clientName: "Finnieston & Co.",
    amount: 1200,
    dueDate: "2026-03-15",
    status: "paid",
    paidAt: "2026-03-14",
    createdAt: "2026-02-15",
  },
  {
    id: "inv7",
    reference: "INV-2026-035",
    clientId: "c5",
    clientName: "West End Wanderlust",
    amount: 1100,
    dueDate: "2026-03-10",
    status: "paid",
    paidAt: "2026-03-11",
    createdAt: "2026-02-10",
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: "l1",
    companyName: "Southside Supper Club",
    contactName: "Jamie Muir",
    contactEmail: "jamie@southsidesupperclub.com",
    value: 950,
    stage: "outreach",
    nextAction: "Follow-up email",
    assignedTo: "Rohit",
    createdAt: "2026-04-10",
    updatedAt: "2026-04-20",
  },
  {
    id: "l2",
    companyName: "Hyndland Yoga Studio",
    contactName: "Priya Sharma",
    contactEmail: "priya@hyndlandyoga.com",
    value: 750,
    stage: "meeting",
    nextAction: "Send proposal",
    assignedTo: "Rohin",
    createdAt: "2026-04-05",
    updatedAt: "2026-04-22",
  },
  {
    id: "l3",
    companyName: "Partick Brewing Co.",
    contactName: "Callum Ross",
    contactEmail: "callum@partickbrewing.com",
    value: 1400,
    stage: "proposal",
    nextAction: "Chase response",
    assignedTo: "Rohit",
    createdAt: "2026-03-25",
    updatedAt: "2026-04-18",
  },
  {
    id: "l4",
    companyName: "Shawlands Skincare",
    contactName: "Lauren Reid",
    contactEmail: "lauren@shawlandsskincare.com",
    value: 1800,
    stage: "negotiation",
    nextAction: "Confirm package scope",
    assignedTo: "Rohin",
    notes: "Wants bespoke content calendar",
    createdAt: "2026-03-15",
    updatedAt: "2026-04-24",
  },
  {
    id: "l5",
    companyName: "Duke Street Deli",
    contactName: "Marco Bianchi",
    contactEmail: "marco@dukestdeli.com",
    value: 850,
    stage: "signed",
    nextAction: "Begin onboarding",
    assignedTo: "Harpreet",
    createdAt: "2026-03-10",
    updatedAt: "2026-04-25",
  },
  {
    id: "l6",
    companyName: "Govanhill Community Hub",
    contactName: "Sandra McLeod",
    value: 600,
    stage: "outreach",
    nextAction: "Send intro deck",
    assignedTo: "Harpreet",
    createdAt: "2026-04-18",
    updatedAt: "2026-04-18",
  },
];

export const MOCK_VIDEOS: Video[] = [
  {
    id: "v1",
    clientId: "c1",
    clientName: "The Kelvin Kitchen",
    title: "Sunday Roast Reel — April",
    platform: "instagram",
    status: "pending",
    productionStage: "editing",
    dueDate: "2026-04-27",
    videoUrl: "#",
    createdAt: "2026-04-20",
  },
  {
    id: "v2",
    clientId: "c2",
    clientName: "Finnieston & Co.",
    title: "Cocktail Menu Launch",
    platform: "tiktok",
    status: "pending",
    productionStage: "filming",
    dueDate: "2026-04-28",
    videoUrl: "#",
    createdAt: "2026-04-21",
  },
  {
    id: "v3",
    clientId: "c5",
    clientName: "West End Wanderlust",
    title: "Glasgow Hidden Gems Part 3",
    platform: "youtube",
    status: "edit_requested",
    productionStage: "review",
    dueDate: "2026-04-26",
    videoUrl: "#",
    feedback: "Please shorten the intro — should be under 5 seconds. Also the music is too loud at 0:45.",
    createdAt: "2026-04-19",
  },
  {
    id: "v4",
    clientId: "c1",
    clientName: "The Kelvin Kitchen",
    title: "Chef Behind the Scenes",
    platform: "instagram",
    status: "approved",
    productionStage: "approved",
    dueDate: "2026-04-22",
    videoUrl: "#",
    createdAt: "2026-04-15",
  },
  {
    id: "v5",
    clientId: "c3",
    clientName: "Glasgow Barbell Club",
    title: "May Training Preview",
    platform: "instagram",
    status: "pending",
    productionStage: "scripting",
    dueDate: "2026-04-29",
    videoUrl: "#",
    createdAt: "2026-04-22",
  },
];

export const MOCK_VIDEO_COMMENTS: Record<string, VideoComment[]> = {
  v1: [
    {
      id: "vc1-1",
      videoId: "v1",
      author: "Rohit",
      role: "team",
      type: "comment",
      message: "Filming wrapped yesterday — really happy with the kitchen shots. Heading into post now.",
      createdAt: "2026-04-21T09:15:00Z",
    },
    {
      id: "vc1-2",
      videoId: "v1",
      author: "Rohin",
      role: "team",
      type: "feedback",
      timecode: "00:30",
      message: "Caption overlays feel slightly off-brand here — cross-check against the style guide before export.",
      createdAt: "2026-04-21T11:30:00Z",
      resolved: false,
    },
  ],
  v2: [
    {
      id: "vc2-1",
      videoId: "v2",
      author: "Rohit",
      role: "team",
      type: "comment",
      message: "Shoot day confirmed for Wednesday evening. Bar access from 6pm — bringing the full lighting kit.",
      createdAt: "2026-04-21T14:00:00Z",
    },
  ],
  v3: [
    {
      id: "vc3-1",
      videoId: "v3",
      author: "Rohin",
      role: "team",
      type: "feedback",
      timecode: "00:12",
      message: "Logo animation is slightly off-centre in this opening frame — adjust the anchor point.",
      createdAt: "2026-04-22T09:00:00Z",
      resolved: true,
    },
    {
      id: "vc3-2",
      videoId: "v3",
      author: "West End Wanderlust",
      role: "client",
      type: "feedback",
      timecode: "00:45",
      message: "The music completely drowns out the voiceover here. Drop it by about 40%. Also the intro needs to be under 5 seconds.",
      createdAt: "2026-04-22T15:45:00Z",
      resolved: false,
    },
    {
      id: "vc3-3",
      videoId: "v3",
      author: "Rohin",
      role: "team",
      type: "comment",
      message: "On it. Will fix the audio balance and trim the intro — new version uploading tonight.",
      createdAt: "2026-04-22T16:20:00Z",
      parentId: "vc3-2",
    },
  ],
  v4: [
    {
      id: "vc4-1",
      videoId: "v4",
      author: "Rohit",
      role: "team",
      type: "comment",
      message: "Final cut is ready. Really pleased with how the slow-mo kitchen shots turned out.",
      createdAt: "2026-04-20T11:00:00Z",
    },
    {
      id: "vc4-2",
      videoId: "v4",
      author: "The Kelvin Kitchen",
      role: "client",
      type: "approval",
      message: "This is brilliant! The vibe is exactly right for the brand.",
      createdAt: "2026-04-20T14:30:00Z",
    },
  ],
  v5: [
    {
      id: "vc5-1",
      videoId: "v5",
      author: "Harpreet",
      role: "team",
      type: "comment",
      message: "Starting on the script for the May training preview. Will share a draft before we book the shoot day.",
      createdAt: "2026-04-22T09:00:00Z",
    },
  ],
};

export const MOCK_CONTENT_ITEMS: ContentItem[] = [
  {
    id: "ci1",
    clientId: "c1",
    clientName: "The Kelvin Kitchen",
    type: "reel",
    title: "Sunday Roast Reel",
    dueDate: "2026-04-27",
    createdAt: "2026-04-10",
  },
  {
    id: "ci2",
    clientId: "c2",
    clientName: "Finnieston & Co.",
    type: "post",
    title: "Bank Holiday Opening Hours",
    dueDate: "2026-04-28",
    createdAt: "2026-04-12",
  },
  {
    id: "ci3",
    clientId: "c5",
    clientName: "West End Wanderlust",
    type: "upload",
    title: "Hidden Gems Part 3",
    dueDate: "2026-04-26",
    createdAt: "2026-04-10",
  },
  {
    id: "ci4",
    clientId: "c3",
    clientName: "Glasgow Barbell Club",
    type: "shoot",
    title: "May Shoot Day",
    dueDate: "2026-05-02",
    createdAt: "2026-04-15",
  },
  {
    id: "ci5",
    clientId: "c1",
    clientName: "The Kelvin Kitchen",
    type: "post",
    title: "Mother's Day Menu",
    dueDate: "2026-05-04",
    createdAt: "2026-04-20",
  },
  {
    id: "ci6",
    clientId: "c2",
    clientName: "Finnieston & Co.",
    type: "reel",
    title: "Cocktail Recipe — Espresso Martini",
    dueDate: "2026-05-05",
    createdAt: "2026-04-22",
  },
];

export const MOCK_QUOTES: Quote[] = [
  {
    id: "q1",
    reference: "QUO-2026-018",
    clientId: "c3",
    clientName: "Glasgow Barbell Club",
    items: [
      { description: "Monthly social media management", quantity: 1, unitPrice: 750 },
      { description: "Reel production (x4)", quantity: 4, unitPrice: 75 },
    ],
    subtotal: 1050,
    vat: 210,
    total: 1260,
    validUntil: "2026-05-26",
    status: "sent",
    createdAt: "2026-04-26",
  },
  {
    id: "q2",
    reference: "QUO-2026-017",
    clientId: "l3",
    clientName: "Partick Brewing Co.",
    items: [
      { description: "Brand Builder package", quantity: 1, unitPrice: 1400 },
    ],
    subtotal: 1400,
    vat: 280,
    total: 1680,
    validUntil: "2026-05-20",
    status: "draft",
    createdAt: "2026-04-20",
  },
];

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: "con1",
    clientId: "c1",
    clientName: "The Kelvin Kitchen",
    package: "Social Growth",
    startDate: "2025-09-01",
    duration: 12,
    status: "signed",
    fileUrl: "#",
    createdAt: "2025-08-28",
  },
  {
    id: "con2",
    clientId: "c2",
    clientName: "Finnieston & Co.",
    package: "Brand Builder",
    startDate: "2025-10-15",
    duration: 12,
    status: "signed",
    fileUrl: "#",
    createdAt: "2025-10-12",
  },
  {
    id: "con3",
    clientId: "c3",
    clientName: "Glasgow Barbell Club",
    package: "Social Growth",
    startDate: "2026-01-10",
    duration: 6,
    status: "sent",
    createdAt: "2026-01-08",
  },
];

export const MOCK_ONBOARDING: Record<string, OnboardingChecklist> = {
  c3: {
    clientId: "c3",
    contract: true,
    payment: true,
    brandAssets: true,
    accessGranted: true,
    kickOffCall: true,
    questionnaire: false,
    firstDraft: false,
    firstPost: false,
  },
  c4: {
    clientId: "c4",
    contract: true,
    payment: false,
    brandAssets: true,
    accessGranted: false,
    kickOffCall: false,
    questionnaire: false,
    firstDraft: false,
    firstPost: false,
  },
};

export const MOCK_DASHBOARD: DashboardStats = {
  mrr: 3900,
  mrrTrend: [
    { month: "Nov", value: 2400 },
    { month: "Dec", value: 2800 },
    { month: "Jan", value: 2800 },
    { month: "Feb", value: 3250 },
    { month: "Mar", value: 3600 },
    { month: "Apr", value: 3900 },
  ],
  unpaidInvoicesCount: 4,
  unpaidInvoicesTotal: 3900,
  pipelineValue: 5600,
  urgentTasksCount: 3,
  pendingVideosCount: 3,
  recentActivity: [
    {
      id: "a1",
      type: "invoice_paid",
      description: "Invoice INV-2026-036 marked as paid — Finnieston & Co. (£1,200)",
      createdAt: "2026-04-25T14:32:00Z",
      userName: "Rohit",
    },
    {
      id: "a2",
      type: "video_approved",
      description: "Video approved — The Kelvin Kitchen: Chef Behind the Scenes",
      createdAt: "2026-04-24T11:15:00Z",
      userName: "Rohin",
    },
    {
      id: "a3",
      type: "lead_moved",
      description: "Lead moved to Negotiation — Shawlands Skincare (£1,800)",
      createdAt: "2026-04-24T09:42:00Z",
      userName: "Rohin",
    },
    {
      id: "a4",
      type: "client_added",
      description: "New client added — Glasgow Barbell Club",
      createdAt: "2026-04-22T16:00:00Z",
      userName: "Harpreet",
    },
    {
      id: "a5",
      type: "quote_sent",
      description: "Quote QUO-2026-018 sent — Glasgow Barbell Club (£1,260)",
      createdAt: "2026-04-21T13:20:00Z",
      userName: "Rohit",
    },
  ],
};

export const CLIENT_COLORS: Record<string, string> = {
  c1: "#EF4444",
  c2: "#3B82F6",
  c3: "#10B981",
  c4: "#F59E0B",
  c5: "#8B5CF6",
  c6: "#EC4899",
};
